services:
  netbird-client:
      container_name: netbird-client
      hostname: pve-lxc-media
      cap_add:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
      network_mode: host
      env_file:
        - .env
      environment:
          - NB_SETUP_KEY=${SETUP_KEY}
      volumes:
          - netbird-client:/var/lib/netbird
      image: netbirdio/netbird:latest
      restart: unless-stopped
volumes:
  netbird-client:
      name: netbird-client
