---
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/emby/library:/config
      - /media/downloads/jellyfin:/data/movies
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8097:8096
      - 8921:8920 #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/vchiq:/dev/vchiq #optional
      # - /dev/video10:/dev/video10 #optional
      # - /dev/video11:/dev/video11 #optional
      # - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
