---
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /media/downloads/jellyfin:/media/data
    ports:
      - 8081:80
      - 443:443
    restart: unless-stopped
