---
services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    user: 1000:1000
    group_add:
      - "110"
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - type: bind
        source: /media/downloads/jellyfin
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.7
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ~/qbittorrent/appdata:/config
      - /media/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
