---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    group_add:
     - '993' # group_id of /dev/dri/renderD128
    environment:
      - TZ=Etc/UTC
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - /mnt/nas/downloads/media:/data/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.7
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ~/qbittorrent/appdata:/config
      - /mnt/nas/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./config:/www/assets # Make sure your local config directory exists
    ports:
      - 80:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: unless-stopped